add :eye_bin to :chruby_map_bins to add compatibility with chruby
Without this line: when using chruby and the capistrano-chruby gem
deployment fails on the `eye:load_config` task due to the
error: `bundle: command not found`

Adding :eye_bin to :chruby_map_bins fixes this issue so that eye-patch
works correctly during capistrano deploys using chruby